Repository cdklabs/construct-hub-webapp, pull requests merged in 2021-06, with the labels that each got.

#69 chore(deps): upgrade projen
  .github/workflows/release.yml
  .github/workflows/upgrade-dependencies.yml
  .github/workflows/upgrade-projen.yml
  .gitignore
  .npmignore
  .projen/deps.json
  .projen/tasks.json
  .versionrc.json
  LICENSE
  package.json
  yarn.lock
Labels: auto-merge

#73 chore: organize folder structure
  src/App.tsx
  src/api/package/assemblies.ts
  src/api/package/util.test.ts
  src/api/package/util.ts
  src/components/GettingStarted/index.tsx
  src/components/Header/index.tsx
  src/components/PackageDocs/index.tsx
  src/components/PackageHeader/index.tsx
  src/contexts/Theme.tsx
  src/stories/PackageHeader.stories.tsx
  src/views/Home/index.tsx
  src/views/Home/style.css
  src/views/NotFound/index.tsx
  src/views/Package/index.tsx
  src/views/PackageLatest/index.tsx
  src/views/Packages/index.tsx
Labels: enhancement

#72 chore(deps): upgrade projen
  .gitattributes
  .github/workflows/upgrade-dependencies.yml
  .github/workflows/upgrade-projen.yml
  .gitignore
  .mergify.yml
  .npmignore
  .projen/deps.json
  .projen/tasks.json
  .versionrc.json
  package.json
  yarn.lock
Labels: auto-merge

#74 feat: useRequest
  .projen/deps.json
  .projen/tasks.json
  .projenrc.js
  package.json
  src/hooks/useRequest.test.ts
  src/hooks/useRequest.ts
  yarn.lock
Labels: enhancement

#79 feat: Package Details Header
  .projen/deps.json
  .projen/tasks.json
  package.json
  src/api/package/metadata.ts
  src/components/DependencyDropdown/index.tsx
  src/components/GettingStarted/index.tsx
  src/components/Header/index.tsx
  src/components/Logo/index.tsx
  src/components/NavLink/index.tsx
  src/components/OperatorArea/index.tsx
  src/components/PackageDetails/index.tsx
  src/components/PackageDocs/index.tsx
  src/components/PackageHeader/index.tsx
  src/components/PublisherArea/index.tsx
  src/views/Package/index.tsx
  yarn.lock
Labels: enhancement

#80 feat: React eslint rules
  .eslintrc.json
  .projen/deps.json
  .projen/tasks.json
  .projenrc.js
  package.json
  src/components/DependencyDropdown/index.tsx
  src/components/Header/index.tsx
  src/components/Logo/index.tsx
  src/components/OperatorArea/index.tsx
  src/components/PackageDocs/Body.tsx
  src/components/PackageDocs/index.tsx
  src/components/PackageHeader/index.tsx
  src/components/PublisherArea/index.tsx
  src/views/Home/index.tsx
  src/views/Package/index.tsx
  yarn.lock
Labels: tooling

#76 feat: storybook addons
  .eslintrc.json
  .projen/deps.json
  .projen/tasks.json
  .projenrc.js
  .storybook/main.js
  .storybook/preview.js
  package.json
  src/components/PackageHeader/index.tsx
  src/contexts/Theme.tsx
  src/stories/PackageHeader.stories.tsx
  yarn.lock
Labels: tooling

#75 feat: cypress test runner
  .projen/deps.json
  .projen/tasks.json
  .projenrc.js
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/Home/home.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  cypress/types/cypress-override.d.ts
  package.json
  src/components/Header/index.tsx
  yarn.lock
Labels: tooling

#85 feat: language bar component
  cypress/support/commands.js
  src/components/Header/index.tsx
  src/components/LanguageBar/LanguageBar.test.tsx
  src/components/LanguageBar/index.tsx
  src/components/OperatorArea/index.tsx
  src/icons/DotNetIcon/index.tsx
  src/icons/GoIcon/index.tsx
  src/icons/JavaIcon/index.tsx
  src/icons/Logo/index.tsx
  src/icons/NodeJsIcon/index.tsx
  src/icons/PythonIcon/index.tsx
  src/icons/TSIcon/index.tsx
  src/stories/LangaugeBar.stories.tsx
Labels: enhancement

#84 feat: date formatting
  .projen/deps.json
  .projen/tasks.json
  .projenrc.js
  package.json
  src/components/OperatorArea/index.tsx
  yarn.lock
Labels: enhancement

#95 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#96 bug: fix safari issue caused by codemaker
  .projen/deps.json
  .projenrc.js
  package.json
  src/api/docgen/transpile/python.ts
  yarn.lock
Labels: bug

#98 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#97 feat: Language Bar UI
  src/App.tsx
  src/components/Card/index.tsx
  src/components/DependencyDropdown/index.tsx
  src/components/GettingStarted/index.tsx
  src/components/LanguageBar/LanguageBar.test.tsx
  src/components/LanguageBar/index.tsx
  src/components/LanguageSelection/DisabledLangPopover.tsx
  src/components/LanguageSelection/index.tsx
  src/components/OperatorArea/index.tsx
  src/components/PackageDetails/index.tsx
  src/components/PackageDocs/index.tsx
  src/components/PackageHeader/index.tsx
  src/components/PackageNav/index.tsx
  src/components/PublisherArea/index.tsx
  src/constants/languages.ts
  src/contexts/Language/Language.test.ts
  src/contexts/Language/Language.tsx
  src/contexts/Language/index.ts
  src/index.tsx
  src/stories/LanguageBar.stories.tsx
  src/views/SearchResults/index.tsx
Labels: enhancement

#103 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#108 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#110 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#107 feat: PWA / service-worker functionality
  .projen/deps.json
  .projenrc.js
  package.json
  public/favicon.ico
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/index.tsx
  src/register-service-worker.ts
  src/service-worker.ts
  yarn.lock
Labels: enhancement

#112 chore(deps): upgrade dependencies
  .github/workflows/build.yml
  package.json
  yarn.lock
Labels: auto-approve

#123 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#126 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#129 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#134 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#132 feat: choose submodule
  .projenrc.js
  src/components/ChooseSubmodule/ChooseSubmodule.test.tsx
  src/components/ChooseSubmodule/ChooseSubmodule.tsx
  src/components/ChooseSubmodule/Result.tsx
  src/components/ChooseSubmodule/SearchInput.test.tsx
  src/components/ChooseSubmodule/SearchInput.tsx
  src/components/ChooseSubmodule/SearchPopover.test.tsx
  src/components/ChooseSubmodule/SearchPopover.tsx
  src/components/ChooseSubmodule/index.ts
  src/components/DependencyDropdown/index.tsx
  src/components/PackageDocs/index.tsx
  src/components/PackageNav/index.tsx
  src/hooks/useDebounce/index.ts
  src/hooks/useDebounce/useDebounce.test.ts
  src/hooks/useDebounce/useDebounce.ts
  src/service-worker.ts
  src/views/Package/index.tsx
Labels: effort/small, enhancement, priority/p0, risk/medium

#141 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#143 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#144 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#145 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#147 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#154 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#146 feat: catalog search component
  .storybook/main.js
  src/components/CatalogSearch/CatalogSearch.stories.tsx
  src/components/CatalogSearch/CatalogSearch.test.tsx
  src/components/CatalogSearch/CatalogSearch.tsx
  src/components/CatalogSearch/Dropdown.tsx
  src/components/CatalogSearch/index.ts
  src/components/LanguageBar/LanguageBar.stories.tsx
  src/components/LanguageBar/LanguageBar.tsx
  src/components/PackageHeader/PackageHeader.stories.tsx
  src/components/PackageNav/PackageNav.stories.tsx
  src/constants/languages.ts
  src/util/createTestIds.ts
Labels: enhancement
