Repository cdklabs/construct-hub-webapp, pull requests merged in 2021-11, with the labels that each got.

#556 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#559 chore(deps): upgrade dependencies
  .eslintrc.json
  package.json
  yarn.lock
Labels: auto-approve

#563 feat: search by author from package page
  src/views/Package/PackageHeader/Details.tsx
Labels: do-not-merge

#566 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#574 chore: cleanup unused exports
  .eslintrc.json
  .projen/deps.json
  .projen/tasks.json
  .projenrc.js
  package.json
  scripts/analyze-exports.js
  scripts/proxy-server.js
  src/api/stats/index.ts
  src/components/CatalogSearch/index.ts
  src/components/CodePopover/CodePopover.tsx
  src/components/CodePopover/CodePopoverTrigger.tsx
  src/components/CodePopover/index.ts
  src/components/NavTree/NavTree.tsx
  src/components/NavTree/index.ts
  src/components/PackageCard/index.ts
  src/icons/Logo.tsx
  src/icons/NodeIcon.tsx
  src/views/FAQ/index.ts
  src/views/Home/index.ts
  src/views/HomeRedesign/HomeSection.tsx
  src/views/HomeRedesign/index.ts
  src/views/Package/DependencyDropdown.tsx
  src/views/Package/LanguageSelection/DisabledLangPopover.tsx
  src/views/Package/PackageDocs.tsx
  src/views/Package/index.ts
  src/views/PackageLatest/PackageLatest.tsx
  src/views/PackageLatest/index.ts
  src/views/Packages/Packages.tsx
  src/views/Packages/index.ts
  src/views/SearchRedesign/index.ts
  src/views/SearchResults/constants.ts
  src/views/SearchResults/index.ts
  src/views/SiteTerms/index.ts
  yarn.lock
Labels: enhancement, tooling

#578 chore(deps): upgrade dependencies
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve

#608 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#607 feat: Review - Package Page
  src/components/Code/SingleLineRenderer.tsx
  src/components/PackageCard/Details.tsx
  src/views/Package/PackageHeader/Details.tsx
  src/views/Package/PackageHeader/Heading.tsx
  src/views/Package/PackageHeader/Install.tsx
  src/views/Package/PackageHeader/PackageHeader.tsx
Labels: do-not-merge

#612 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#613 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#622 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#624 chore: upgrade some dependencies
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-main.yml
  .projen/deps.json
  .projenrc.js
  package.json
  yarn.lock
Labels: auto-merge, auto-approve

#636 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#642 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#640 feat: keywords filter
  src/api/catalog-search/catalog-search.test.ts
  src/api/catalog-search/catalog-search.ts
  src/api/catalog-search/util.test.ts
  src/api/catalog-search/util.ts
  src/components/PackageCard/Tags.tsx
  src/components/PackageTag/PackageTag.tsx
  src/constants/url.ts
  src/hooks/useCatalogResults/useCatalogResults.ts
  src/hooks/useCatalogSearch/useCatalogSearch.ts
  src/util/url.ts
  src/views/Package/PackageHeader/Heading.tsx
  src/views/SearchRedesign/CheckboxFilter.tsx
  src/views/SearchRedesign/FilterPanel.tsx
  src/views/SearchRedesign/KeywordsFilter.tsx
  src/views/SearchRedesign/SearchResults.tsx
  src/views/SearchRedesign/SearchState.tsx
  src/views/SearchRedesign/SortAndFilterDrawer.tsx
Labels: do-not-merge

#650 feat: search relevance tuning
  src/api/catalog-search/__snapshots__/catalog-search.test.ts.snap
  src/api/catalog-search/catalog-search.ts
Labels: enhancement, do-not-merge

#651 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#658 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#660 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#665 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#680 chore(deps): upgrade dependencies
  .gitattributes
  .github/workflows/pull-request-lint.yml
  .gitignore
  package.json
  yarn.lock
Labels: auto-approve

#689 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#700 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#698 feat: updates card layout
  src/components/PackageCard/Details.tsx
  src/components/PackageCard/EditorsNote.tsx
  src/components/PackageCard/Heading.tsx
  src/components/PackageCard/Highlight.tsx
  src/components/PackageCard/WideCard.tsx
  src/views/Home/Featured.tsx
  src/views/Home/PackageGrid.tsx
Labels: do-not-merge

#712 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#730 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#731 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#735 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#748 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#772 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#787 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#788 chore(deps): upgrade dependencies
  .gitignore
  package.json
  src/api/catalog-search/util.ts
  src/components/LanguageSupportTooltip/LanguageSupportTooltip.tsx
  src/contexts/ExternalLinkWarning/ExternalLinkWarningModal.tsx
  src/views/SearchRedesign/SearchDetails.tsx
  yarn.lock
Labels: auto-approve

#794 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve
