Repository cdklabs/construct-hub-webapp, pull requests merged in 2021-10, with the labels that each got.

#453 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#456 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#457 chore(deps): upgrade dependencies
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/upgrade.yml
  package.json
  yarn.lock
Labels: auto-approve

#459 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#461 chore(deps): upgrade dependencies
  .gitattributes
  .github/workflows/release.yml
  .github/workflows/upgrade-main.yml
  .gitignore
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve

#469 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#473 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#476 bug: some package languages are undefined and not handled
  src/api/catalog-search/util.test.ts
  src/api/catalog-search/util.ts
  src/api/package/packages.ts
  src/components/PackageCard/PackageCard.tsx
  src/components/PackageLanguages/PackageLanguages.tsx
Labels: bug, priority/p0

#478 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#475 feat: new search bar
  cypress/integration/header.spec.ts
  cypress/integration/home.spec.ts
  cypress/integration/search.spec.ts
  cypress/support/commands.ts
  src/App.tsx
  src/api/catalog-search/catalog-search.ts
  src/api/catalog-search/util.ts
  src/components/CatalogSearch/CatalogSearch.tsx
  src/components/CatalogSearch/CatalogSearchInputs.tsx
  src/components/Header/Header.tsx
  src/components/Header/HeaderSearch.tsx
  src/components/Header/SearchButton.tsx
  src/components/Header/testIds.ts
  src/components/PackageCard/Heading.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/SearchOverlay.tsx
  src/components/SearchBar/SearchSuggestions.tsx
  src/components/SearchBar/index.ts
  src/components/SearchBar/testIds.ts
  src/components/SearchItem/SearchItem.tsx
  src/components/SearchModal/SearchModal.tsx
  src/hooks/useCatalogSearch/useCatalogSearch.ts
  src/views/HomeRedesign/Hero.tsx
  src/views/HomeRedesign/HomeRedesign.tsx
  src/views/HomeRedesign/testIds.ts
  src/views/SearchRedesign/CDKFilter.tsx
  src/views/SearchRedesign/SearchRedesign.tsx
  src/views/SearchRedesign/SearchResults.tsx
  src/views/SearchRedesign/testIds.ts
Labels: do-not-merge

#484 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#485 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#487 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#488 chore(deps): upgrade dependencies
  .eslintrc.json
  .gitattributes
  .gitignore
  .npmignore
  package.json
  tsconfig.dev.json
  tsconfig.json
  yarn.lock
Labels: auto-approve

#490 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#493 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#494 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#495 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#496 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#502 chore(deps): upgrade dependencies
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve

#505 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#507 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#554 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#555 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve
